version: '3.1'

services:
  db:
    image: postgres:13.1
    privileged: true
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django_1
      POSTGRES_DB: notes

  backend:
    build:
      context: notes
    ports:
      - 8080:8080
#    expose:
#      - 8080
    command: bash -c "./wait-for-postgres.sh db && python manage.py migrate && python manage.py create_users && python manage.py & gunicorn notes.wsgi -b 0.0.0.0:8080"
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - backend

  frontend:
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - nginx